config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root "pages#home"
  get '/about', to: 'pages#about', as: 'about'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 100}
    validates :body, presence: true, length: {minimum: 6, maximum: 100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    set_article
    if @article.nil?
      # Handle the case where the article doesn't exist
      # For example, display an error message or redirect to a different page
    else
      # Proceed with the deletion logic
      @article.destroy
      redirect_to articles_path, notice: "Article was successfully destroyed."
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    respond_to do |format|
      format.html # Render the default HTML template (home.html.erb)
    end
  end

  def about
    respond_to do |format|
      format.html
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

</div>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2> The fallowing errors prevented the article from being saved:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg| %>
 
    <li><%= msg %></li>

    <% end %>
 </ul>
<% end %>

<%= form_with(model: @article, local: true)  do |f| %>



<p>
<%= f.label :title %> <br/>
<%= f.text_field :title %>
</p>

<p>
<%= f.label :description %> <br/>
<%= f.text_area :description %>
</p>

<p>
<%= f.label :body %>
<%= f.text_field :body %>
</p>

<p>
<%= f.submit %>
</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to "Cancel and return to articles listing", articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing page!</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Body</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= article.body %></td>
    <td>
      <%= link_to 'Show', article_path(article) %>
      <%= link_to 'Edit', edit_article_path(article) %>
      <%= link_to 'Delete', article_path(article), turbo_method: :delete, data: { turbo_method: :delete }, data: { confirm: "Are you sure?" } %>
    </td>
  </tr>
<% end %>

  </tbody>
</table>
<p>
  <%= link_to "Create new article", new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>
<%= render 'form' %>

<%= link_to "Return to articles listing", articles_path %>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/layouts/_messages.html.erb
 <% flash.each do |name, msg| %>
    <%= msg %>
   <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Blog_01</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  
  </head>

  <body>

 <%= render 'layouts/messages'%>
  <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

<%= link_to "Articles listing", articles_path %> |
<%= link_to "Home page", root_path %>

app/views/pages/home.html.erb
<h1>Welcome to the Home page</h1>

<%= link_to "Articles listing", articles_path %> |
<%= link_to "About page", about_path %>